package com.github.artyomcool.lodinfra;

import org.apache.commons.compress.archivers.zip.*;
import org.apache.poi.ooxml.POIXMLDocument;
import org.apache.poi.xddf.usermodel.chart.XDDFChart;
import org.apache.poi.xdgf.xml.XDGFXMLDocumentPart;
import org.apache.poi.xslf.usermodel.*;
import org.apache.poi.xssf.model.*;
import org.apache.poi.xssf.usermodel.*;
import org.apache.poi.xwpf.usermodel.*;
import org.apache.xmlbeans.StringEnumAbstractBase;
import org.apache.xmlbeans.impl.schema.SchemaTypeSystemImpl;
import org.apache.xmlbeans.impl.store.*;
import org.apache.xmlbeans.impl.values.StringEnumValue;
import org.graalvm.nativeimage.hosted.Feature;
import org.graalvm.nativeimage.hosted.RuntimeReflection;
import org.openxmlformats.schemas.spreadsheetml.x2006.main.STCellType;
import org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.*;

import java.util.Arrays;

public class NativeImage implements Feature {
    public void beforeAnalysis(BeforeAnalysisAccess access) {

        Arrays.asList(

                AsiExtraField.class,
                X5455_ExtendedTimestamp.class,
                X7875_NewUnix.class,
                JarMarker.class,
                UnicodePathExtraField.class,
                UnicodeCommentExtraField.class,
                Zip64ExtendedInformationExtraField.class,
                X000A_NTFS.class,
                X0014_X509Certificates.class,
                X0015_CertificateIdForFile.class,
                X0016_CertificateIdForCentralDirectory.class,
                X0017_StrongEncryptionHeader.class,
                X0019_EncryptionRecipientCertificateList.class,
                ResourceAlignmentExtraField.class,

                CalcChainDocumentImpl.class,
                ChartsheetDocumentImpl.class,
                CommentsDocumentImpl.class,
                ExternalLinkDocumentImpl.class,
                MapInfoDocumentImpl.class,
                SingleXmlCellsDocumentImpl.class,
                SstDocumentImpl.class,
                STAxisImpl.class,
                STBorderIdImpl.class,
                STBorderStyleImpl.class,
                STCalcModeImpl.class,
                STCellCommentsImpl.class,
                STCellFormulaTypeImpl.class,
                STCellRefImpl.class,
                STCellStyleXfIdImpl.class,
                STCellTypeImpl.class,
                STCfTypeImpl.class,
                STCfvoTypeImpl.class,
                STConditionalFormattingOperatorImpl.class,
                STDataConsolidateFunctionImpl.class,
                STDataValidationErrorStyleImpl.class,
                STDataValidationOperatorImpl.class,
                STDataValidationTypeImpl.class,
                STDxfIdImpl.class,
                STFillIdImpl.class,
                STFontIdImpl.class,
                STFontSchemeImpl.class,
                STFormulaImpl.class,
                STHorizontalAlignmentImpl.class,
                STIconSetTypeImpl.class,
                STItemTypeImpl.class,
                STNumFmtIdImpl.class,
                STOrientationImpl.class,
                STPageOrderImpl.class,
                STPaneImpl.class,
                STPaneStateImpl.class,
                STPatternTypeImpl.class,
                STRefImpl.class,
                STSheetStateImpl.class,
                STSourceTypeImpl.class,
                STSqrefImpl.class,
                STTableStyleTypeImpl.class,
                STUnderlineValuesImpl.class,
                STUnsignedIntHexImpl.class,
                STUnsignedShortHexImpl.class,
                STVerticalAlignmentImpl.class,
                STXmlDataTypeImpl.class,
                StyleSheetDocumentImpl.class,
                TableDocumentImpl.class,
                WorkbookDocumentImpl.class,
                WorksheetDocumentImpl.class,

                XSLFComments.class,
                XDGFXMLDocumentPart.class,
                XSSFPivotTable.class,
                XWPFAbstractFootnotesEndnotes.class,
                StylesTable.class,
                XSLFObjectData.class,
                ThemesTable.class,
                XSSFPivotCacheDefinition.class,
                XSLFSheet.class,
                XWPFHeaderFooter.class,
                XSLFTheme.class,
                XWPFStyles.class,
                XSLFCommentAuthors.class,
                XSLFTableStyles.class,
                XSSFPictureData.class,
                XSSFVMLDrawing.class,
                CommentsTable.class,
                XSSFVBAPart.class,
                XSSFTable.class,
                XWPFSettings.class,
                XDDFChart.class,
                XSSFPivotCache.class,
                SingleXmlCells.class,
                MapInfo.class,
                ExternalLinksTable.class,
                XSSFDrawing.class,
                POIXMLDocument.class,
                XSSFSheet.class,
                SharedStringsTable.class,
                XWPFPictureData.class,
                XWPFNumbering.class,
                XSLFPictureData.class,
                XSSFPivotCacheRecords.class,
                CalculationChain.class,
                CTAuthorsImpl.class,
                CTAutoFilterImpl.class,
                CTBookViewImpl.class,
                CTBookViewsImpl.class,
                CTBooleanPropertyImpl.class,
                CTBorderImpl.class,
                CTBorderPrImpl.class,
                CTBordersImpl.class,
                CTBreakImpl.class,
                CTCacheFieldImpl.class,
                CTCacheFieldsImpl.class,
                CTCacheSourceImpl.class,
                CTCalcCellImpl.class,
                CTCalcChainImpl.class,
                CTCalcPrImpl.class,
                CTCellAlignmentImpl.class,
                CTCellFormulaImpl.class,
                CTCellImpl.class,
                CTCellProtectionImpl.class,
                CTCellStyleXfsImpl.class,
                CTCellXfsImpl.class,
                CTCfRuleImpl.class,
                CTCfvoImpl.class,
                CTChartsheetImpl.class,
                CTColFieldsImpl.class,
                CTColImpl.class,
                CTColorImpl.class,
                CTColorScaleImpl.class,
                CTColorsImpl.class,
                CTColsImpl.class,
                CTCommentImpl.class,
                CTCommentListImpl.class,
                CTCommentsImpl.class,
                CTConditionalFormattingImpl.class,
                CTDataBarImpl.class,
                CTDataFieldImpl.class,
                CTDataFieldsImpl.class,
                CTDataValidationImpl.class,
                CTDataValidationsImpl.class,
                CTDefinedNameImpl.class,
                CTDefinedNamesImpl.class,
                CTDialogsheetImpl.class,
                CTDrawingImpl.class,
                CTDxfImpl.class,
                CTDxfsImpl.class,
                CTExternalBookImpl.class,
                CTExternalDefinedNameImpl.class,
                CTExternalDefinedNamesImpl.class,
                CTExternalLinkImpl.class,
                CTExternalReferenceImpl.class,
                CTExternalReferencesImpl.class,
                CTExternalSheetNameImpl.class,
                CTExternalSheetNamesImpl.class,
                CTFieldImpl.class,
                CTFillImpl.class,
                CTFillsImpl.class,
                CTFontImpl.class,
                CTFontNameImpl.class,
                CTFontSchemeImpl.class,
                CTFontsImpl.class,
                CTFontSizeImpl.class,
                CTHeaderFooterImpl.class,
                CTHyperlinkImpl.class,
                CTHyperlinksImpl.class,
                CTIconSetImpl.class,
                CTIgnoredErrorImpl.class,
                CTIgnoredErrorsImpl.class,
                CTIndexedColorsImpl.class,
                CTIntPropertyImpl.class,
                CTItemImpl.class,
                CTItemsImpl.class,
                CTLegacyDrawingImpl.class,
                CTLocationImpl.class,
                CTMapImpl.class,
                CTMapInfoImpl.class,
                CTMergeCellImpl.class,
                CTMergeCellsImpl.class,
                CTNumFmtImpl.class,
                CTNumFmtsImpl.class,
                CTOleObjectImpl.class,
                CTOleObjectsImpl.class,
                CTOutlinePrImpl.class,
                CTPageBreakImpl.class,
                CTPageFieldImpl.class,
                CTPageFieldsImpl.class,
                CTPageMarginsImpl.class,
                CTPageSetupImpl.class,
                CTPageSetUpPrImpl.class,
                CTPaneImpl.class,
                CTPatternFillImpl.class,
                CTPhoneticPrImpl.class,
                CTPhoneticRunImpl.class,
                CTPivotCacheDefinitionImpl.class,
                CTPivotCacheImpl.class,
                CTPivotCacheRecordsImpl.class,
                CTPivotCachesImpl.class,
                CTPivotFieldImpl.class,
                CTPivotFieldsImpl.class,
                CTPivotTableDefinitionImpl.class,
                CTPivotTableStyleImpl.class,
                CTPrintOptionsImpl.class,
                CTREltImpl.class,
                CTRgbColorImpl.class,
                CTRowFieldsImpl.class,
                CTRowImpl.class,
                CTRPrEltImpl.class,
                CTRstImpl.class,
                CTSchemaImpl.class,
                CTSelectionImpl.class,
                CTSharedItemsImpl.class,
                CTSheetCalcPrImpl.class,
                CTSheetDataImpl.class,
                CTSheetDimensionImpl.class,
                CTSheetFormatPrImpl.class,
                CTSheetImpl.class,
                CTSheetPrImpl.class,
                CTSheetProtectionImpl.class,
                CTSheetsImpl.class,
                CTSheetViewImpl.class,
                CTSheetViewsImpl.class,
                CTSingleXmlCellImpl.class,
                CTSingleXmlCellsImpl.class,
                CTSstImpl.class,
                CTStylesheetImpl.class,
                CTTableColumnImpl.class,
                CTTableColumnsImpl.class,
                CTTableImpl.class,
                CTTablePartImpl.class,
                CTTablePartsImpl.class,
                CTTableStyleElementImpl.class,
                CTTableStyleImpl.class,
                CTTableStyleInfoImpl.class,
                CTTableStylesImpl.class,
                CTUnderlinePropertyImpl.class,
                CTVerticalAlignFontPropertyImpl.class,
                CTWorkbookImpl.class,
                CTWorkbookPrImpl.class,
                CTWorkbookProtectionImpl.class,
                CTWorksheetImpl.class,
                CTWorksheetSourceImpl.class,
                CTXfImpl.class,
                CTXmlCellPrImpl.class,
                CTXmlColumnPrImpl.class,
                CTXmlPrImpl.class,
                CTStylesheetImpl.class,
                StringEnumValue.class,
                StringEnumAbstractBase.class,
                SchemaTypeSystemImpl.class
        ).forEach(a -> {
            RuntimeReflection.register(a);
            RuntimeReflection.register(a.getDeclaredConstructors());
        });

        Arrays.asList(
                Locale.class,
                Path.class,
                CharUtil.class,
                Cursor.class,
                Jsr173.class,
                Locale.class,
                Path.class,
                PathDelegate.class,
                Public2.class,
                QNameFactory.class,
                Query.class,
                QueryDelegate.class,
                Saaj.class,
                STCellType.Enum.class,
                schemaorg_apache_xmlbeans.system.sD023D6490046BA0250A839A9AD24C443.TypeSystemHolder.class
        ).forEach(a -> {
            RuntimeReflection.register(a);
            RuntimeReflection.register(a.getDeclaredConstructors());
            RuntimeReflection.register(a.getMethods());
            RuntimeReflection.register(a.getDeclaredMethods());
            RuntimeReflection.register(a.getDeclaredFields());
        });
    }
}